apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
    environment: dev
spec:
  containers:
  - name: mongo
    image: mongo
    ports:
      - containerPort: 27017
    volumeMounts:
      - name: mongo-data
        mountPath: /data/db
    volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data